const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let DB,ACH,run=[],music=null,deferredInstall=null,swReg=null;
const L=[['Novato de Academia',10],['Senpai Otaku',15],['Elite Shonen',20],['Lenda do Multiverso',25]], STEP=[1,3,5,7], COOL=[50,75,100,125];
const S={screen:'home',mode:'main',level:0,q:0,lives:3,xp:0,combo:0,maxCombo:0,correct:0,answered:0,errors:0,levelErrors:0,bossWins:0,maxTimeHits:0,timeouts34:0,reachedOneLife:false,bet:false,locked:false,timer:null,time:0,startAt:0,shownAt:0,responseTotal:0,timedAnswers:0,cats:new Set(),animes:new Set(),duelSeed:null,duelTarget:null,levels:[]};
const st={g(k,d){try{return JSON.parse(localStorage.getItem('qnweb_'+k))??d}catch{return d}},s(k,v){localStorage.setItem('qnweb_'+k,JSON.stringify(v))}};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const shuffle=(a,r=Math.random)=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function rng(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function hash(s){let h=2166136261;for(let c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function shell(c,nav=true){return '<div class="app"><div class="bg"></div><div class="shell">'+c+'</div>'+(nav?navBar():'')+'</div>'}
function navBar(){return '<div class="navWrap"><nav class="nav glass"><button data-nav="home" class="'+(S.screen==='home'?'active':'')+'"><span>⌂</span>INÍCIO</button><button data-nav="play"><span>🎮</span>JOGAR</button><button data-nav="ach"><span>📖</span>COLEÇÃO</button><button data-nav="shop"><span>🛒</span>LOJA</button><button data-nav="community"><span>♧</span>COMUNIDADE</button></nav></div>'}
function stopMusic(){if(music){music.pause();music=null}}
function playMusic(kind){stopMusic();if(document.hidden)return;music=new Audio(kind==='game'?'./primeiro_desafio.mp3':'./portal_nerdora.mp3');music.loop=true;music.volume=kind==='game'?.29:.25;music.play().catch(()=>{})}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2400)}
function clearTimer(){if(S.timer){clearInterval(S.timer);S.timer=null}}
function limit(){if(S.level===3&&S.bet)return 8;if(S.level===2)return 20;if(S.level===3)return 15;return null}
function startClock(reset=true){clearTimer();const lim=limit();if(lim==null){S.time=0;renderHud();return}if(reset)S.time=lim;S.timer=setInterval(()=>{if(S.locked||document.hidden)return;S.time--;renderHud();if(S.time<=0){clearTimer();answer(null,true)}},1000)}
function timeBonus(){if(S.level===2)return S.time>15?4:S.time>10?3:S.time>5?1:0;if(S.level===3)return S.time>10?4:S.time>5?2:0;return 0}
function pickLevel(li,rand=Math.random){const level=DB.levels[li], total=L[li][1], recent=new Set(st.g('recent_'+li,[]));let normal=level.questions.filter(q=>!q.boss_eligible), boss=level.questions.filter(q=>q.boss_eligible&&q.difficulty_band===3);if(!normal.length)normal=level.questions;if(!boss.length)boss=level.questions.filter(q=>q.difficulty_band===3);if(!boss.length)boss=level.questions;let out=[],anime={};
for(const band of [1,2,3]){let pool=shuffle(normal.filter(q=>q.difficulty_band===band),rand);for(const q of pool){if(out.length>=total-1)break;if(out.some(x=>x.fact_id===q.fact_id)||recent.has(q.fact_id))continue;if((anime[q.anime]||0)>=2)continue;out.push(q);anime[q.anime]=(anime[q.anime]||0)+1}}
for(const q of shuffle(normal,rand)){if(out.length>=total-1)break;if(!out.some(x=>x.fact_id===q.fact_id)){out.push(q);anime[q.anime]=(anime[q.anime]||0)+1}}
let b=shuffle(boss.filter(q=>!out.some(x=>x.fact_id===q.fact_id)),rand)[0]||shuffle(boss,rand)[0];out=[...out.slice(0,total-1),b];st.s('recent_'+li,[...st.g('recent_'+li,[]),...out.map(q=>q.fact_id)].slice(-COOL[li]));return out}
function reset(mode){clearTimer();Object.assign(S,{mode,level:0,q:0,lives:3,xp:0,combo:0,maxCombo:0,correct:0,answered:0,errors:0,levelErrors:0,bossWins:0,maxTimeHits:0,timeouts34:0,reachedOneLife:false,bet:false,locked:false,time:0,startAt:Date.now(),shownAt:0,responseTotal:0,timedAnswers:0,cats:new Set(),animes:new Set(),duelSeed:null,duelTarget:null,levels:[]})}
function home(){S.screen='home';clearTimer();playMusic('menu');const unlocked=st.g('unlocked',[]).length;app.innerHTML=shell('<div class="top"><div class="profile glass"><img class="avatar" src="./icon.png"><div><h3>SakuraGeek</h3><div class="rank">👑 Mestre de Todas as Categorias</div><div class="xpbar"><i></i></div></div></div><div class="tools"><button class="round" data-install>⬇</button><button class="round">⚙</button></div></div><section class="hero"><div class="heroText"><div class="logo"><span>QUIZ</span><span>NERDORA</span></div><div class="tag">CONHECIMENTO TAMBÉM É PODER</div></div></section><button class="play" data-action="main">🎮 JOGAR »</button><div class="grid4"><button class="feature orange" data-action="daily"><div class="ico">🗓</div><b>DESAFIO DIÁRIO</b><small>NOVOS DESAFIOS TODO DIA</small></button><button class="feature blue" data-action="duel"><div class="ico">⚔</div><b>DUELO OTAKU</b><small>DESAFIE POR CÓDIGO</small></button><button class="feature pink" data-action="ranking"><div class="ico">🏆</div><b>RANKING</b><small>VEJA SEUS MELHORES</small></button><button class="feature purple" data-action="ach"><div class="ico">✦</div><b>CONQUISTAS</b><small>'+unlocked+'/40 PERMANENTES</small></button></div><div class="status"><div class="glass"><div class="kicker">👑 TÍTULO ATUAL</div><b>Mestre do Duelo</b><small>Seu título atual</small></div><div class="glass"><div class="kicker">NÍVEL 28</div><div class="xpbar"><i></i></div><small>320 / 500 XP</small></div></div><div class="quote glass">“Aqui, cada pergunta é um novo nível na sua jornada otaku!” <b>— Nerdola</b></div><div class="version">Quiz Nerdora • v0.15.1 restaurada</div>');bind()}
function current(){return run[S.q]}
function boss(){return S.mode==='main'&&S.q===run.length-1}
function startMain(){reset('main');S.level=0;run=pickLevel(0);playMusic('game');question()}
function dailySet(){const key=new Date().toISOString().slice(0,10),r=rng(hash(key));let out=[],lv=[];for(let i=0;i<4;i++){const p=shuffle(DB.levels[i].questions,r).slice(0,5);out.push(...p);lv.push(...p.map(()=>i))}return{out,lv}}
function startDaily(){const key=new Date().toISOString().slice(0,10);if(st.g('dailyDate','')===key){ranking(true);return}reset('daily');const d=dailySet();run=d.out;S.levels=d.lv;S.level=S.levels[0];playMusic('game');question()}
function duelSet(seed){const r=rng(seed);let out=[],lv=[];[2,2,3,3].forEach((n,i)=>{const p=pickLevel(i,r).slice(0,n);out.push(...p);lv.push(...p.map(()=>i))});return{out,lv}}
function createDuel(){reset('duel');S.duelSeed=(Math.random()*0xffffffff)>>>0;const d=duelSet(S.duelSeed);run=d.out;S.levels=d.lv;S.level=S.levels[0];playMusic('game');question()}
function duelCode(seed,xp){const raw='NDR-'+seed.toString(36).toUpperCase()+'-'+xp.toString(36).toUpperCase();return raw+'-'+(hash(raw)%46656).toString(36).toUpperCase().padStart(3,'0')}
function parseCode(c){const p=c.trim().toUpperCase().split('-');if(p.length!==4||p[0]!=='NDR')return null;const seed=parseInt(p[1],36),xp=parseInt(p[2],36),raw=p.slice(0,3).join('-');return (hash(raw)%46656).toString(36).toUpperCase().padStart(3,'0')===p[3]?{seed,xp}:null}
function acceptDuel(){const p=parseCode($('#duelInput').value);if(!p)return toast('Código inválido.');reset('duel');S.duelSeed=p.seed;S.duelTarget=p.xp;const d=duelSet(p.seed);run=d.out;S.levels=d.lv;S.level=S.levels[0];playMusic('game');question()}
function question(skipBet=false){clearTimer();if(S.mode!=='main')S.level=S.levels[S.q]??S.level;if(S.mode==='main'&&S.level===3&&boss()&&!S.bet&&!skipBet)return betScreen();S.screen='play';S.locked=false;const q=current(),lim=limit();app.innerHTML=shell('<div class="head"><div><div class="sub">'+(S.mode==='daily'?'DESAFIO DIÁRIO':S.mode==='duel'?'DUELO OTAKU':L[S.level][0])+'</div><h1>'+(boss()?'BOSS QUESTION':'QUIZ NERDORA')+'</h1><small>Pergunta '+(S.q+1)+'/'+run.length+'</small></div><button class="back" data-nav="home">←</button></div><div class="hud"><div class="glass hearts" id="lives"></div><div class="glass">COMBO <b id="combo"></b></div><div class="glass"><b id="xp"></b> • <span id="timer"></span></div></div><div class="qcard glass '+(boss()?'boss':'')+'">'+(boss()?'<div class="bossbar">⚠ BOSS • +50 XP</div>':'')+'<div class="meta">'+esc(q.anime)+' • '+esc(q.category)+'</div><div class="question">'+esc(q.question||q.text)+'</div><div class="answers">'+shuffle(q.options).map(o=>'<button class="answer" data-answer="'+o.id+'"><strong>'+o.id+'</strong><span>'+esc(o.text)+'</span></button>').join('')+'</div><div id="feedback"></div></div>');bind();renderHud();S.shownAt=Date.now();startClock(true)}
function renderHud(){if(!$('#lives'))return;$('#lives').textContent='♥'.repeat(S.lives)+'♡'.repeat(3-S.lives);$('#combo').textContent='x'+S.combo;$('#xp').textContent=S.xp+' XP';$('#timer').textContent=limit()==null?'∞':S.time+'s'}
function answer(id,timeout=false){if(S.locked)return;S.locked=true;clearTimer();const q=current(),ok=id===q.correct_option,isBoss=boss();S.answered++;S.responseTotal+=Math.max(0,Date.now()-S.shownAt);S.timedAnswers++;$$('.answer').forEach(b=>{b.disabled=true;if(b.dataset.answer===q.correct_option)b.classList.add('correct');else if(b.dataset.answer===id)b.classList.add('wrong')});let msg='';
if(ok){let gain=10+S.combo*STEP[S.level]+timeBonus()+(isBoss?50:0)+(isBoss&&S.bet?100:0);S.xp+=gain;S.correct++;S.combo++;S.maxCombo=Math.max(S.maxCombo,S.combo);S.cats.add(q.category);S.animes.add(q.anime);if(isBoss){S.bossWins++;let totalBoss=st.g('bossWinsTotal',0)+1;st.s('bossWinsTotal',totalBoss);if(totalBoss>=100)unlock('boss_executioner_100')}if(timeBonus()===4)S.maxTimeHits++;msg='<div class="feedback good"><b>'+(isBoss?(S.bet?'APOSTA VENCIDA!':'BOSS DERROTADO!'):'ACERTOU!')+'</b> +'+gain+' XP</div>';checkAch(q,isBoss)}else{S.errors++;S.levelErrors++;S.combo=0;if(S.level>=2&&timeout)S.timeouts34++;if(S.bet&&isBoss)S.lives=0;else S.lives=Math.max(0,S.lives-1);if(S.lives===1)S.reachedOneLife=true;msg='<div class="feedback bad"><b>'+(timeout?'TEMPO ESGOTADO':'ERROU')+'</b> '+(S.bet&&isBoss?'RUN ENCERRADA':'-1 VIDA • COMBO ZERADO')+'</div>'}$('#feedback').outerHTML=msg;renderHud();setTimeout(()=>S.lives<=0?finish(false):next(),1150)}
function next(){if(S.mode==='main'){if(S.q>=run.length-1)return finishLevel();S.q++;question()}else{if(S.q>=run.length-1)return finish(false);S.q++;question()}}
function finishLevel(){if(S.levelErrors===0){unlock('no_room_for_error');let p=new Set(st.g('perfectLevels',[]));p.add(S.level);st.s('perfectLevels',[...p]);if(p.size>=4)unlock('four_perfect_domains')}if(S.level===3)return finish(true);S.lives=Math.min(3,S.lives+1);S.level++;S.q=0;S.levelErrors=0;run=pickLevel(S.level);intermission()}
function intermission(){S.screen='intermission';clearTimer();app.innerHTML=shell('<div class="modal"><div class="modalBox glass center"><div class="big">'+(S.level+1)+'</div><div class="sub">PORTAL LIBERADO</div><h2>'+L[S.level][0]+'</h2><p>+1 vida recuperada, até o máximo de 3.</p><button class="next" data-action="continue">ESTOU PRONTO</button></div></div>',false);bind()}
function betScreen(){S.screen='bet';clearTimer();app.innerHTML=shell('<div class="modal"><div class="modalBox glass center"><div class="sub" style="color:var(--red)">ÚLTIMO BOSS</div><h2>APOSTA OTAKU</h2><div class="hearts" style="font-size:26px">'+('♥'.repeat(S.lives)+'♡'.repeat(3-S.lives))+'</div><p>Normal: 15 segundos e +50 XP.<br><b>Aposta:</b> 8 segundos, +50 Boss +100 XP. Errou ou acabou o tempo? A run termina.</p><div class="row"><button class="next" data-action="normal">NORMAL</button><button class="next" data-action="bet">APOSTAR</button></div></div></div>',false);bind()}
function unlock(id){let u=new Set(st.g('unlocked',[]));if(u.has(id))return;u.add(id);st.s('unlocked',[...u]);const a=ACH.permanent.find(x=>x[0]===id);if(a)toast('CONQUISTA: '+a[2])}
function checkAch(q,isBoss){if(S.combo>=10)unlock('perfect_flow');if(S.combo>=20)unlock('beyond_limit');if(S.combo>=30)unlock('multiverse_combo');if(S.combo>=40)unlock('never_break_rhythm');if(S.bet&&isBoss){unlock('all_or_nothing');let n=st.g('betsWon',0)+1;st.s('betsWon',n);if(n>=10)unlock('portal_gambler');if(n>=50)unlock('fearless_end')}if(limit()!=null&&S.time===1)unlock('last_second_eyes');if(S.cats.size>=6)unlock('all_categories_master');let an=new Set(st.g('correctAnimes',[]));an.add(q.anime);st.s('correctAnimes',[...an]);if(an.size>=50)unlock('world_collector');if(an.size>=100)unlock('boundless_knowledge')}
function finish(victory){clearTimer();if(S.mode==='daily'){const key=new Date().toISOString().slice(0,10);st.s('dailyDate',key);st.s('dailyScore',S.xp);let last=st.g('lastDaily',''), streak=st.g('dailyStreak',0);if(last){let d=Math.round((new Date(key)-new Date(last))/86400000);streak=d===1?streak+1:d===0?streak:1}else streak=1;st.s('lastDaily',key);st.s('dailyStreak',streak);st.s('dailyCount',st.g('dailyCount',0)+1);if(streak>=7)unlock('otaku_discipline');if(streak>=30)unlock('no_missing_episode');if(st.g('dailyCount',0)>=365)unlock('portals_365');return result('DESAFIO DIÁRIO CONCLUÍDO')}
if(S.mode==='duel'){let won=S.duelTarget!=null&&S.xp>S.duelTarget;if(S.duelTarget!=null){let streak=won?st.g('duelStreak',0)+1:0;st.s('duelStreak',streak);if(streak>=10)unlock('portal_undefeated')}if(won){let w=st.g('duelWins',0)+1;st.s('duelWins',w);unlock('duel_challenger');if(w>=25)unlock('dangerous_rival');if(w>=100)unlock('otaku_nemesis')}return result(S.duelTarget==null?'DUELO CRIADO':won?'DUELO VENCIDO':S.xp===S.duelTarget?'EMPATE':'DUELO ENCERRADO',S.duelTarget==null?duelCode(S.duelSeed,S.xp):null)}
st.s('runs',st.g('runs',0)+1);unlock('first_portal_jump');if(victory){unlock('four_trials_survivor');if(S.lives===1)unlock('immortal_heart');if(S.reachedOneLife)unlock('impossible_return');if(S.correct===70&&S.answered===70)unlock('multiverse_oracle');if(S.bossWins>=4)unlock('boss_hunter_run');if(S.maxTimeHits>=15)unlock('otaku_reflex');if(S.timeouts34===0)unlock('broken_stopwatch');if(Date.now()-S.startAt<480000)unlock('lightning_ascension');let acc=S.correct/Math.max(1,S.answered)*100;if(acc>=95){unlock('surgical_precision');let n=st.g('high95',0)+1;st.s('high95',n);if(n>=5)unlock('ninety_nine_not_enough')}}if(st.g('runs',0)>=100)unlock('portal_knows_me');if(st.g('runs',0)>=500)unlock('multiverse_inhabitant');result(victory?'VITÓRIA NO MULTIVERSO!':'RUN ENCERRADA')}
function result(title,code=null){S.screen='result';playMusic('menu');const acc=Math.round(S.correct/Math.max(1,S.answered)*100);let best=st.g('bestXp',0);if(S.mode==='main'&&S.xp>best){if(best>0){let rb=st.g('recordBreaks',0)+1;st.s('recordBreaks',rb);if(rb>=10)unlock('record_hunter');if(rb>=25)unlock('yesterday_limit')}st.s('bestXp',S.xp);}app.innerHTML=shell('<div class="head"><div><div class="sub">RESULTADO</div><h1>'+title+'</h1></div><button class="back" data-nav="home">←</button></div><div class="panel glass center"><div class="big">'+S.xp+' XP</div></div><div class="stats"><div class="stat glass"><small>ACERTOS</small><b>'+S.correct+'/'+S.answered+'</b></div><div class="stat glass"><small>PRECISÃO</small><b>'+acc+'%</b></div><div class="stat glass"><small>MAIOR COMBO</small><b>x'+S.maxCombo+'</b></div><div class="stat glass"><small>VIDAS</small><b>'+S.lives+'/3</b></div></div>'+(code?'<div class="panel glass"><h3>Código do Duelo</h3><div class="duelcode">'+code+'</div></div>':'')+'<button class="next" data-nav="home">VOLTAR AO PORTAL</button>');bind()}
function ranking(daily=false){S.screen='ranking';playMusic('menu');const best=daily?st.g('dailyScore',0):st.g('bestXp',0);app.innerHTML=shell('<div class="head"><div><div class="sub">PRESTÍGIO</div><h1>RANKING OTAKU</h1></div><button class="back" data-nav="home">←</button></div><div class="rankrow glass"><b>#1</b><div><b>@você</b><small style="display:block;color:var(--muted)">Placar local real</small></div><b>'+best+' XP</b></div><div class="panel glass center"><small>Sem jogadores fictícios. O ranking online será conectado ao backend.</small></div>');bind()}
function achievements(tab='permanent'){S.screen='ach';playMusic('menu');app.innerHTML=shell('<div class="head"><div><div class="sub">COLEÇÃO</div><h1>CONQUISTAS</h1><small>40 permanentes • 20 temporárias</small></div><button class="back" data-nav="home">←</button></div><div class="tabs"><button class="tab '+(tab==='permanent'?'active':'')+'" data-tab="permanent">PERMANENTES</button><button class="tab '+(tab==='temporary'?'active':'')+'" data-tab="temporary">TEMPORÁRIAS</button></div><div id="achgrid" class="achgrid"></div>');renderAchievements(tab);bind()}
function renderAchievements(tab){const grid=$('#achgrid');if(!grid)return;const u=new Set(st.g('unlocked',[])),list=tab==='temporary'?ACH.temporary:ACH.permanent;grid.innerHTML=list.map(a=>{const on=u.has(a[0]),secret=['impossible_return','last_second_eyes'].includes(a[0]);return '<div class="ach glass '+(on?'unlocked':'')+'"><div class="ico">'+((on||!secret)?a[1]:'❓')+'</div><h4>'+esc((on||!secret)?a[2]:'???')+'</h4><p>'+esc((on||!secret)?a[3]:'Conquista secreta.')+'</p><span class="badge '+(a[4]==='server'||tab==='temporary'?'server':'')+'">'+(tab==='temporary'?'TEMPORÁRIA • SERVIDOR':a[4]==='server'?'VALIDAÇÃO SERVIDOR':on?'DESBLOQUEADA':'BLOQUEADA')+'</span></div>'}).join('')}
function duel(){S.screen='duel';playMusic('menu');app.innerHTML=shell('<div class="head"><div><div class="sub">CONFRONTO</div><h1>DUELO OTAKU</h1><small>Mesma sequência • código sem respostas</small></div><button class="back" data-nav="home">←</button></div><div class="panel glass"><h3>Criar desafio</h3><p>Jogue 10 perguntas e gere um código com seed e XP-alvo.</p><button class="next" data-action="createDuel">CRIAR E JOGAR</button></div><div class="panel glass"><h3>Aceitar desafio</h3><input id="duelInput" class="input" placeholder="NDR-..."><button class="next" data-action="acceptDuel">ENTRAR NO DUELO</button></div>');bind()}
async function install(){if(matchMedia('(display-mode:standalone)').matches)return;if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice.catch(()=>{});deferredInstall=null}else toast('No Chrome, use ⋮ → Instalar app.')}
function bind(){$$('[data-nav]').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;if(n==='home')home();if(n==='play')startMain();if(n==='ach')achievements();if(n==='shop'||n==='community')toast('Integração com Nerdora em desenvolvimento.')} );$$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='main')startMain();if(a==='daily')startDaily();if(a==='duel')duel();if(a==='ranking')ranking();if(a==='ach')achievements();if(a==='continue')question();if(a==='normal'){S.bet=false;question(true)}if(a==='bet'){S.bet=true;question(true)}if(a==='createDuel')createDuel();if(a==='acceptDuel')acceptDuel()});$$('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer));$$('[data-tab]').forEach(b=>b.onclick=()=>achievements(b.dataset.tab));$$('[data-install]').forEach(b=>b.onclick=install)}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopMusic();clearTimer()}else{if(S.screen==='play'){playMusic('game');if(!S.locked&&limit()!=null)startClock(false)}else playMusic('menu')}});
window.addEventListener('pagehide',()=>{stopMusic();clearTimer()});
window.addEventListener('freeze',()=>{stopMusic();clearTimer()});
window.addEventListener('blur',()=>{if(document.hidden){stopMusic();clearTimer()}});
async function updates(){if(!('serviceWorker'in navigator))return;swReg=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});let re=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!re){re=true;location.reload()}});const check=async()=>{try{const v=await fetch('./version.json?t='+Date.now(),{cache:'no-store'}).then(r=>r.json());const old=st.g('build','');if(old&&old!==v.build){$('#updateToast')?.classList.remove('hidden');await swReg.update();if(swReg.waiting)swReg.waiting.postMessage({type:'SKIP_WAITING'})}st.s('build',v.build)}catch{}};await check();setInterval(check,300000);window.addEventListener('focus',check);window.addEventListener('online',check)}
async function init(){try{[DB,ACH]=await Promise.all([fetch('./quiz_questions.json',{cache:'no-store'}).then(r=>r.json()),fetch('./achievements.json',{cache:'no-store'}).then(r=>r.json())]);home();updates()}catch(e){app.innerHTML='<div style="padding:24px;color:white">Erro ao carregar o Quiz Nerdora.</div>'}}
init();